// Package entity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package entity

import (
	"time"
)

// Customer Клиент, которому будет приходить рассылка
type Customer struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	Operator string `json:"operator"`
	Phone    string `json:"phone"`
	Tag      string `json:"tag"`
}

// Error defines model for Error.
type Error struct {
	Code string `json:"code"`
	Desc string `json:"desc"`
}

// Message defines model for Message.
type Message struct {
	CustomerId     string     `json:"customer_id"`
	Id             int        `json:"id"`
	Phone          string     `json:"phone"`
	Sent           *time.Time `json:"sent,omitempty"`
	Status         string     `json:"status"`
	SubscriptionId string     `json:"subscription_id"`
	Text           string     `json:"text"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	// Desc Описание рассылки, просто для чего она создавалась и тд.
	Desc           string    `json:"desc"`
	End            time.Time `json:"end"`
	Id             string    `json:"id"`
	OperatorFilter string    `json:"operator_filter"`
	PhoneFilter    string    `json:"phone_filter"`
	Start          time.Time `json:"start"`
	TagFilter      string    `json:"tag_filter"`

	// Text Текст сообщения в рассылке
	Text string `json:"text"`
}

// CreateClientJSONRequestBody defines body for CreateClient for application/json ContentType.
type CreateClientJSONRequestBody = Customer

// UpdateClientJSONRequestBody defines body for UpdateClient for application/json ContentType.
type UpdateClientJSONRequestBody = Customer

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = Subscription

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = Subscription
