apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: send
  name: send
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: send
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (46dcb9181)
      creationTimestamp: null
      labels:
        io.kompose.network/deploy-default: "true"
        io.kompose.service: send
    spec:
      containers:
        - env:
            - name: ENDPOINT_TOKEN
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA1NDQwMDksImlzcyI6ImZhYnJpcXVlIiwibmFtZSI6Imh0dHBzOi8vdC5tZS90aGVmcm9sIn0.JBeHeTpnbDUKnKdQi2ujFrAq6NDghwUEBpBriuk2YJw
            - name: NOTTY_DSN
              value: host=db user=notty password=notty.notty.1 dbname=notty
          image: send
          name: send
          resources: {}
      restartPolicy: Always
status: {}
