apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (46dcb9181)
      creationTimestamp: null
      labels:
        io.kompose.network/deploy-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: NOTTY_DSN
              value: host=db user=notty password=notty.notty.1 dbname=notty
          image: web
          name: web
          ports:
            - containerPort: 8080
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
