package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i gitlab.com/thefrol/notty/internal/app/worker.Sender -o ./internal/mock/sender_mock.go -n SenderMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"gitlab.com/thefrol/notty/internal/entity"
)

// SenderMock implements worker.Sender
type SenderMock struct {
	t minimock.Tester

	funcSend          func(m1 entity.Message) (err error)
	inspectFuncSend   func(m1 entity.Message)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mSenderMockSend

	funcWork          func(ch1 <-chan entity.Message) (ch2 <-chan entity.Message, err error)
	inspectFuncWork   func(ch1 <-chan entity.Message)
	afterWorkCounter  uint64
	beforeWorkCounter uint64
	WorkMock          mSenderMockWork
}

// NewSenderMock returns a mock for worker.Sender
func NewSenderMock(t minimock.Tester) *SenderMock {
	m := &SenderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mSenderMockSend{mock: m}
	m.SendMock.callArgs = []*SenderMockSendParams{}

	m.WorkMock = mSenderMockWork{mock: m}
	m.WorkMock.callArgs = []*SenderMockWorkParams{}

	return m
}

type mSenderMockSend struct {
	mock               *SenderMock
	defaultExpectation *SenderMockSendExpectation
	expectations       []*SenderMockSendExpectation

	callArgs []*SenderMockSendParams
	mutex    sync.RWMutex
}

// SenderMockSendExpectation specifies expectation struct of the Sender.Send
type SenderMockSendExpectation struct {
	mock    *SenderMock
	params  *SenderMockSendParams
	results *SenderMockSendResults
	Counter uint64
}

// SenderMockSendParams contains parameters of the Sender.Send
type SenderMockSendParams struct {
	m1 entity.Message
}

// SenderMockSendResults contains results of the Sender.Send
type SenderMockSendResults struct {
	err error
}

// Expect sets up expected params for Sender.Send
func (mmSend *mSenderMockSend) Expect(m1 entity.Message) *mSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &SenderMockSendExpectation{}
	}

	mmSend.defaultExpectation.params = &SenderMockSendParams{m1}
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the Sender.Send
func (mmSend *mSenderMockSend) Inspect(f func(m1 entity.Message)) *mSenderMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for SenderMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by Sender.Send
func (mmSend *mSenderMockSend) Return(err error) *SenderMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &SenderMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &SenderMockSendResults{err}
	return mmSend.mock
}

// Set uses given function f to mock the Sender.Send method
func (mmSend *mSenderMockSend) Set(f func(m1 entity.Message) (err error)) *SenderMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the Sender.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the Sender.Send method")
	}

	mmSend.mock.funcSend = f
	return mmSend.mock
}

// When sets expectation for the Sender.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mSenderMockSend) When(m1 entity.Message) *SenderMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SenderMock.Send mock is already set by Set")
	}

	expectation := &SenderMockSendExpectation{
		mock:   mmSend.mock,
		params: &SenderMockSendParams{m1},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up Sender.Send return parameters for the expectation previously defined by the When method
func (e *SenderMockSendExpectation) Then(err error) *SenderMock {
	e.results = &SenderMockSendResults{err}
	return e.mock
}

// Send implements worker.Sender
func (mmSend *SenderMock) Send(m1 entity.Message) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(m1)
	}

	mm_params := &SenderMockSendParams{m1}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_got := SenderMockSendParams{m1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("SenderMock.Send got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the SenderMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(m1)
	}
	mmSend.t.Fatalf("Unexpected call to SenderMock.Send. %v", m1)
	return
}

// SendAfterCounter returns a count of finished SenderMock.Send invocations
func (mmSend *SenderMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of SenderMock.Send invocations
func (mmSend *SenderMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mSenderMockSend) Calls() []*SenderMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*SenderMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockSendDone() bool {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendInspect logs each unmet expectation
func (m *SenderMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.Send with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to SenderMock.Send")
		} else {
			m.t.Errorf("Expected call to SenderMock.Send with params: %#v", *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		m.t.Error("Expected call to SenderMock.Send")
	}
}

type mSenderMockWork struct {
	mock               *SenderMock
	defaultExpectation *SenderMockWorkExpectation
	expectations       []*SenderMockWorkExpectation

	callArgs []*SenderMockWorkParams
	mutex    sync.RWMutex
}

// SenderMockWorkExpectation specifies expectation struct of the Sender.Work
type SenderMockWorkExpectation struct {
	mock    *SenderMock
	params  *SenderMockWorkParams
	results *SenderMockWorkResults
	Counter uint64
}

// SenderMockWorkParams contains parameters of the Sender.Work
type SenderMockWorkParams struct {
	ch1 <-chan entity.Message
}

// SenderMockWorkResults contains results of the Sender.Work
type SenderMockWorkResults struct {
	ch2 <-chan entity.Message
	err error
}

// Expect sets up expected params for Sender.Work
func (mmWork *mSenderMockWork) Expect(ch1 <-chan entity.Message) *mSenderMockWork {
	if mmWork.mock.funcWork != nil {
		mmWork.mock.t.Fatalf("SenderMock.Work mock is already set by Set")
	}

	if mmWork.defaultExpectation == nil {
		mmWork.defaultExpectation = &SenderMockWorkExpectation{}
	}

	mmWork.defaultExpectation.params = &SenderMockWorkParams{ch1}
	for _, e := range mmWork.expectations {
		if minimock.Equal(e.params, mmWork.defaultExpectation.params) {
			mmWork.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWork.defaultExpectation.params)
		}
	}

	return mmWork
}

// Inspect accepts an inspector function that has same arguments as the Sender.Work
func (mmWork *mSenderMockWork) Inspect(f func(ch1 <-chan entity.Message)) *mSenderMockWork {
	if mmWork.mock.inspectFuncWork != nil {
		mmWork.mock.t.Fatalf("Inspect function is already set for SenderMock.Work")
	}

	mmWork.mock.inspectFuncWork = f

	return mmWork
}

// Return sets up results that will be returned by Sender.Work
func (mmWork *mSenderMockWork) Return(ch2 <-chan entity.Message, err error) *SenderMock {
	if mmWork.mock.funcWork != nil {
		mmWork.mock.t.Fatalf("SenderMock.Work mock is already set by Set")
	}

	if mmWork.defaultExpectation == nil {
		mmWork.defaultExpectation = &SenderMockWorkExpectation{mock: mmWork.mock}
	}
	mmWork.defaultExpectation.results = &SenderMockWorkResults{ch2, err}
	return mmWork.mock
}

// Set uses given function f to mock the Sender.Work method
func (mmWork *mSenderMockWork) Set(f func(ch1 <-chan entity.Message) (ch2 <-chan entity.Message, err error)) *SenderMock {
	if mmWork.defaultExpectation != nil {
		mmWork.mock.t.Fatalf("Default expectation is already set for the Sender.Work method")
	}

	if len(mmWork.expectations) > 0 {
		mmWork.mock.t.Fatalf("Some expectations are already set for the Sender.Work method")
	}

	mmWork.mock.funcWork = f
	return mmWork.mock
}

// When sets expectation for the Sender.Work which will trigger the result defined by the following
// Then helper
func (mmWork *mSenderMockWork) When(ch1 <-chan entity.Message) *SenderMockWorkExpectation {
	if mmWork.mock.funcWork != nil {
		mmWork.mock.t.Fatalf("SenderMock.Work mock is already set by Set")
	}

	expectation := &SenderMockWorkExpectation{
		mock:   mmWork.mock,
		params: &SenderMockWorkParams{ch1},
	}
	mmWork.expectations = append(mmWork.expectations, expectation)
	return expectation
}

// Then sets up Sender.Work return parameters for the expectation previously defined by the When method
func (e *SenderMockWorkExpectation) Then(ch2 <-chan entity.Message, err error) *SenderMock {
	e.results = &SenderMockWorkResults{ch2, err}
	return e.mock
}

// Work implements worker.Sender
func (mmWork *SenderMock) Work(ch1 <-chan entity.Message) (ch2 <-chan entity.Message, err error) {
	mm_atomic.AddUint64(&mmWork.beforeWorkCounter, 1)
	defer mm_atomic.AddUint64(&mmWork.afterWorkCounter, 1)

	if mmWork.inspectFuncWork != nil {
		mmWork.inspectFuncWork(ch1)
	}

	mm_params := &SenderMockWorkParams{ch1}

	// Record call args
	mmWork.WorkMock.mutex.Lock()
	mmWork.WorkMock.callArgs = append(mmWork.WorkMock.callArgs, mm_params)
	mmWork.WorkMock.mutex.Unlock()

	for _, e := range mmWork.WorkMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ch2, e.results.err
		}
	}

	if mmWork.WorkMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWork.WorkMock.defaultExpectation.Counter, 1)
		mm_want := mmWork.WorkMock.defaultExpectation.params
		mm_got := SenderMockWorkParams{ch1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWork.t.Errorf("SenderMock.Work got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWork.WorkMock.defaultExpectation.results
		if mm_results == nil {
			mmWork.t.Fatal("No results are set for the SenderMock.Work")
		}
		return (*mm_results).ch2, (*mm_results).err
	}
	if mmWork.funcWork != nil {
		return mmWork.funcWork(ch1)
	}
	mmWork.t.Fatalf("Unexpected call to SenderMock.Work. %v", ch1)
	return
}

// WorkAfterCounter returns a count of finished SenderMock.Work invocations
func (mmWork *SenderMock) WorkAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWork.afterWorkCounter)
}

// WorkBeforeCounter returns a count of SenderMock.Work invocations
func (mmWork *SenderMock) WorkBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWork.beforeWorkCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.Work.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWork *mSenderMockWork) Calls() []*SenderMockWorkParams {
	mmWork.mutex.RLock()

	argCopy := make([]*SenderMockWorkParams, len(mmWork.callArgs))
	copy(argCopy, mmWork.callArgs)

	mmWork.mutex.RUnlock()

	return argCopy
}

// MinimockWorkDone returns true if the count of the Work invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockWorkDone() bool {
	for _, e := range m.WorkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WorkMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWorkCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWork != nil && mm_atomic.LoadUint64(&m.afterWorkCounter) < 1 {
		return false
	}
	return true
}

// MinimockWorkInspect logs each unmet expectation
func (m *SenderMock) MinimockWorkInspect() {
	for _, e := range m.WorkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.Work with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WorkMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWorkCounter) < 1 {
		if m.WorkMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to SenderMock.Work")
		} else {
			m.t.Errorf("Expected call to SenderMock.Work with params: %#v", *m.WorkMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWork != nil && mm_atomic.LoadUint64(&m.afterWorkCounter) < 1 {
		m.t.Error("Expected call to SenderMock.Work")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SenderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendInspect()

		m.MinimockWorkInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone() &&
		m.MinimockWorkDone()
}
