package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i gitlab.com/thefrol/notty/internal/app.SMSer -o ./internal/mock/sm_ser_mock.go -n SMSerMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"gitlab.com/thefrol/notty/internal/entity"
)

// SMSerMock implements app.SMSer
type SMSerMock struct {
	t minimock.Tester

	funcSend          func(m1 entity.Message) (err error)
	inspectFuncSend   func(m1 entity.Message)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mSMSerMockSend
}

// NewSMSerMock returns a mock for app.SMSer
func NewSMSerMock(t minimock.Tester) *SMSerMock {
	m := &SMSerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mSMSerMockSend{mock: m}
	m.SendMock.callArgs = []*SMSerMockSendParams{}

	return m
}

type mSMSerMockSend struct {
	mock               *SMSerMock
	defaultExpectation *SMSerMockSendExpectation
	expectations       []*SMSerMockSendExpectation

	callArgs []*SMSerMockSendParams
	mutex    sync.RWMutex
}

// SMSerMockSendExpectation specifies expectation struct of the SMSer.Send
type SMSerMockSendExpectation struct {
	mock    *SMSerMock
	params  *SMSerMockSendParams
	results *SMSerMockSendResults
	Counter uint64
}

// SMSerMockSendParams contains parameters of the SMSer.Send
type SMSerMockSendParams struct {
	m1 entity.Message
}

// SMSerMockSendResults contains results of the SMSer.Send
type SMSerMockSendResults struct {
	err error
}

// Expect sets up expected params for SMSer.Send
func (mmSend *mSMSerMockSend) Expect(m1 entity.Message) *mSMSerMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SMSerMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &SMSerMockSendExpectation{}
	}

	mmSend.defaultExpectation.params = &SMSerMockSendParams{m1}
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the SMSer.Send
func (mmSend *mSMSerMockSend) Inspect(f func(m1 entity.Message)) *mSMSerMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for SMSerMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by SMSer.Send
func (mmSend *mSMSerMockSend) Return(err error) *SMSerMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SMSerMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &SMSerMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &SMSerMockSendResults{err}
	return mmSend.mock
}

// Set uses given function f to mock the SMSer.Send method
func (mmSend *mSMSerMockSend) Set(f func(m1 entity.Message) (err error)) *SMSerMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the SMSer.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the SMSer.Send method")
	}

	mmSend.mock.funcSend = f
	return mmSend.mock
}

// When sets expectation for the SMSer.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mSMSerMockSend) When(m1 entity.Message) *SMSerMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("SMSerMock.Send mock is already set by Set")
	}

	expectation := &SMSerMockSendExpectation{
		mock:   mmSend.mock,
		params: &SMSerMockSendParams{m1},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up SMSer.Send return parameters for the expectation previously defined by the When method
func (e *SMSerMockSendExpectation) Then(err error) *SMSerMock {
	e.results = &SMSerMockSendResults{err}
	return e.mock
}

// Send implements app.SMSer
func (mmSend *SMSerMock) Send(m1 entity.Message) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(m1)
	}

	mm_params := &SMSerMockSendParams{m1}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_got := SMSerMockSendParams{m1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("SMSerMock.Send got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the SMSerMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(m1)
	}
	mmSend.t.Fatalf("Unexpected call to SMSerMock.Send. %v", m1)
	return
}

// SendAfterCounter returns a count of finished SMSerMock.Send invocations
func (mmSend *SMSerMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of SMSerMock.Send invocations
func (mmSend *SMSerMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to SMSerMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mSMSerMockSend) Calls() []*SMSerMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*SMSerMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *SMSerMock) MinimockSendDone() bool {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendInspect logs each unmet expectation
func (m *SMSerMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SMSerMock.Send with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to SMSerMock.Send")
		} else {
			m.t.Errorf("Expected call to SMSerMock.Send with params: %#v", *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		m.t.Error("Expected call to SMSerMock.Send")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SMSerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SMSerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SMSerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
