openapi: 3.0.0
info:
  title: Нотти. Сервис смс-уведомлений
  version: '1.0'
  description: |
    Отправит уведомления с фильтрацией по тегам и    операторам. Не пропускает мат.     За счет конкурентности готов отправлять по миллиону сообщений в минуту.

    Через  добавляются клиенты и рассылки. У каждой рассылки можно указать время начала и окончания. Если рассылка сейчас активна, то из клиентов отфильтруются те, что подходят по тегам и операторам, и отправит им сообщение.

    Под капотом база данных с двумя микросервисами. Один держит веб-интерфейс, другой проверяет базу и отправляет сообщения. 
paths:
  /customer/{Id}:
    get:
      operationId: GetClient
      tags:
        - customer
      description: Позволяет получить клиента по айдишнику
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: полученный клиент
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: DeleteClient
      description: Удаление клиента по айдишнику
      tags:
        - customer
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
    post:
      operationId: UpdateClient
      description: Обновить клиента по айди
      tags:
        - customer
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Данные для изменения клиента не прошли валидацию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: клиента не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка при создании клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /customer:
    post:
      operationId: CreateClient
      tags:
        - customer
      description: Создает клиента. Айдишник можно указывать, а можно не указывать
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '207':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Данные для создания клиента не прошли валидацию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка при создании клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sub/{Id}:
    get:
      operationId: GetSubscription
      tags:
        - subscription
      description: 'Получить рассылку по айдишнику'
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: DeleteSubscription
      tags:
        - subscription
      description: 'Удалить рассылку'
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Удалено
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Не найдена такая подписка
          content:
            text/plaint:
              schema:
                type: string
        '500':
          description: Ошибка при удалении
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: UpdateSubscription
      tags:
        - subscription
      description: Обновить рассылку
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Запрос неправильно сформирован, например данные не прошли валидацию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка при создании
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sub/{Id}/stats:
    get:
      operationId: SubscriptionStats
      tags:
        - subscription
      description: 'Возвращает статистику по текущей рассылке. Сколько отправлено и получено'
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema: # map[string]
                type: object
                additionalProperties: 
                  type: integer
        '400':
          description: Запрос неправильно сформирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sub:
    post:
      operationId: CreateSubscription
      tags:
        - subscription
      description: Создать рассылку. Если не указать айдишник, то создастся UUID
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Запрос неправильно сформирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка при создании
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message/{Id}:
    get:
      operationId: GetMessage
      tags:
        - message
      description: 'получает данные о сообщении'
      parameters:
        - in: path
          name: Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Customer:
      type: object
      description: Клиент, которому будет приходить рассылка. Имеет номер телефона, имя оператора и тег, по которому его сможет найти рассылка.
      required:
        - id
        - phone
        - tag
        - operator
        - name
      properties:
        id:
          type: string
          description: айдишник сообщения, английские буквы и тире. Подойдет UUID
          example: ivan-testov
        name:
          type: string
          desctiption: имя человека
          example: Иван Тестов
        phone:
          type: string
          description: номер телефона в формате +71112223344
          example: "+79161112233"
        tag:
          type: string
          description: тег, по которому можно будет таргетировать рассылку
          example: moscow-best
        operator:
          type: string
          description: оператор, строка 
          example: mts
    Subscription:
      description: Не смотря на название, это сущности рассылки. Имеет время начала, до которого сообщения рассылаться не будут, и время окончания, после которого тоже не будут рассылаться сообщения. Есть фильтр по тегам и оператору, которые работают в формате постревкого ILIKE. 
      type: object
      required:
        - id
        - start
        - end
        - operator_filter
        - phone_filter
        - tag_filter
        - desc
        - text
      properties:
        id:
          type: string
          description: айдишник, английские буквы и тире. Может быть UUID
          example: send-to-best-clients
        start:
          type: string
          format: date-time
          description: время начала, до этого времени рассылаться не будет
        end:
          type: string
          format: date-time
          description: время окончания, после этого времени рассылаться не будет
        phone_filter:
          type: string
          description: фильтр по номеру телефона, сейчас не используется
        operator_filter:
          type: string
          description: фильтр по оператору, работает как ILIKE в SQL
          example: '%'
        tag_filter:
          description: фильтр по оператору, работает как ILIKE в SQL
          type: string
          example: 'moscow-%'
        desc:
          description: Описание рассылки, просто для чего она создавалась и тд.
          type: string
          example: 'Рассылка кредитов нахаляву'
        text:
          example: Добрый день! Вам одобрен кредит по 0%
          description: Текст сообщения в рассылке
          type: string
    Message:
      type: object
      required:
        - id
        - customer_id
        - subscription_id
        - text
        - phone
        - status
      properties:
        id:
          type: string
        customer_id:
          type: string
        subscription_id:
          type: string
        text:
          type: string
        phone:
          type: string
        status:
          type: string
        sent:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - code
        - desc
      properties:
        code:
          type: string
        desc:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: customer
    description: Конкретный человек, у него есть номер телефона и тег. По этим тегам можно потом таргетировать рассылку
  - name: subscription
    description: 
  - name: message
    description: Сообщение
